export interface PossibleTypesResultData {
  possibleTypes: {
    [key: string]: string[];
  };
}
const result: PossibleTypesResultData = {
  possibleTypes: {
    Attribute: ['SimpleAttribute', 'VariationAttribute'],
    CartError: ['CartItemError'],
    CartItem: ['SimpleCartItem'],
    CartItemConnection: ['CartToCartItemConnection'],
    CartItemConnectionEdge: ['CartToCartItemConnectionEdge'],
    CartItemConnectionPageInfo: ['CartToCartItemConnectionPageInfo'],
    CategoryConnection: [
      'CategoryToAncestorsCategoryConnection',
      'CategoryToCategoryConnection',
      'PostToCategoryConnection',
      'RootQueryToCategoryConnection',
    ],
    CategoryConnectionEdge: [
      'CategoryToAncestorsCategoryConnectionEdge',
      'CategoryToCategoryConnectionEdge',
      'CategoryToParentCategoryConnectionEdge',
      'PostToCategoryConnectionEdge',
      'RootQueryToCategoryConnectionEdge',
    ],
    CategoryConnectionPageInfo: [
      'CategoryToAncestorsCategoryConnectionPageInfo',
      'CategoryToCategoryConnectionPageInfo',
      'PostToCategoryConnectionPageInfo',
      'RootQueryToCategoryConnectionPageInfo',
    ],
    CommentConnection: [
      'CommentToCommentConnection',
      'MediaItemToCommentConnection',
      'OrderToCommentConnection',
      'PageToCommentConnection',
      'PostToCommentConnection',
      'ProductToCommentConnection',
      'ProductToCommentsConnection',
      'RootQueryToCommentConnection',
      'UserToCommentConnection',
    ],
    CommentConnectionEdge: [
      'CommentToCommentConnectionEdge',
      'CommentToParentCommentConnectionEdge',
      'MediaItemToCommentConnectionEdge',
      'OrderToCommentConnectionEdge',
      'PageToCommentConnectionEdge',
      'PostToCommentConnectionEdge',
      'ProductToCommentConnectionEdge',
      'ProductToCommentsConnectionEdge',
      'RootQueryToCommentConnectionEdge',
      'UserToCommentConnectionEdge',
    ],
    CommentConnectionPageInfo: [
      'CommentToCommentConnectionPageInfo',
      'MediaItemToCommentConnectionPageInfo',
      'OrderToCommentConnectionPageInfo',
      'PageToCommentConnectionPageInfo',
      'PostToCommentConnectionPageInfo',
      'ProductToCommentConnectionPageInfo',
      'ProductToCommentsConnectionPageInfo',
      'RootQueryToCommentConnectionPageInfo',
      'UserToCommentConnectionPageInfo',
    ],
    Commenter: ['CommentAuthor', 'User'],
    CommenterConnectionEdge: ['CommentToCommenterConnectionEdge'],
    Connection: [
      'CartToCartItemConnection',
      'CategoryToAncestorsCategoryConnection',
      'CategoryToCategoryConnection',
      'CategoryToContentNodeConnection',
      'CategoryToPostConnection',
      'CommentToCommentConnection',
      'ContentNodeToEnqueuedScriptConnection',
      'ContentNodeToEnqueuedStylesheetConnection',
      'ContentTypeToContentNodeConnection',
      'ContentTypeToTaxonomyConnection',
      'CouponToCustomerConnection',
      'CouponToExcludedProductCategoriesConnection',
      'CouponToExcludedProductsConnection',
      'CouponToProductCategoryConnection',
      'CouponToProductUnionConnection',
      'CustomerToDownloadableItemConnection',
      'CustomerToOrderConnection',
      'CustomerToRefundConnection',
      'GlobalProductAttributeToTermNodeConnection',
      'GroupProductToProductUnionConnection',
      'HierarchicalContentNodeToContentNodeAncestorsConnection',
      'HierarchicalContentNodeToContentNodeChildrenConnection',
      'MediaItemToCommentConnection',
      'MenuItemToMenuItemConnection',
      'MenuToMenuItemConnection',
      'OrderToCommentConnection',
      'OrderToCouponLineConnection',
      'OrderToDownloadableItemConnection',
      'OrderToFeeLineConnection',
      'OrderToLineItemConnection',
      'OrderToRefundConnection',
      'OrderToShippingLineConnection',
      'OrderToTaxLineConnection',
      'PaBacklightsToContentNodeConnection',
      'PaBacklightsToProductConnection',
      'PaBacklightsToProductVariationConnection',
      'PaColorToContentNodeConnection',
      'PaColorToProductConnection',
      'PaColorToProductVariationConnection',
      'PageToCommentConnection',
      'PageToRevisionConnection',
      'PaGlubinaToContentNodeConnection',
      'PaGlubinaToProductConnection',
      'PaGlubinaToProductVariationConnection',
      'PaShadowGapToContentNodeConnection',
      'PaShadowGapToProductConnection',
      'PaShadowGapToProductVariationConnection',
      'PaWidthToContentNodeConnection',
      'PaWidthToProductConnection',
      'PaWidthToProductVariationConnection',
      'PostFormatToContentNodeConnection',
      'PostFormatToPostConnection',
      'PostToCategoryConnection',
      'PostToCommentConnection',
      'PostToPostConnection',
      'PostToPostFormatConnection',
      'PostToRevisionConnection',
      'PostToTagConnection',
      'PostToTermNodeConnection',
      'ProductCategoryToAncestorsProductCategoryConnection',
      'ProductCategoryToContentNodeConnection',
      'ProductCategoryToProductCategoryConnection',
      'ProductCategoryToProductConnection',
      'ProductTagToContentNodeConnection',
      'ProductTagToProductConnection',
      'ProductToCommentConnection',
      'ProductToCommentsConnection',
      'ProductToGlobalProductAttributeConnection',
      'ProductToLocalProductAttributeConnection',
      'ProductToMediaItemConnection',
      'ProductToPaBacklightsConnection',
      'ProductToPaColorConnection',
      'ProductToPaGlubinaConnection',
      'ProductToPaShadowGapConnection',
      'ProductToPaWidthConnection',
      'ProductToProductCategoryConnection',
      'ProductToProductTagConnection',
      'ProductToProductTypeConnection',
      'ProductToProductUnionConnection',
      'ProductToShippingClassConnection',
      'ProductToTermNodeConnection',
      'ProductToUpsellConnection',
      'ProductToVisibleProductConnection',
      'ProductTypeToContentNodeConnection',
      'ProductTypeToProductConnection',
      'ProductVariationToVariationAttributeConnection',
      'ProductWithAttributesToProductAttributeConnection',
      'ProductWithAttributesToVariationAttributeConnection',
      'ProductWithVariationsToProductVariationConnection',
      'RootQueryToCategoryConnection',
      'RootQueryToCommentConnection',
      'RootQueryToContentNodeConnection',
      'RootQueryToContentTypeConnection',
      'RootQueryToCouponConnection',
      'RootQueryToCustomerConnection',
      'RootQueryToEnqueuedScriptConnection',
      'RootQueryToEnqueuedStylesheetConnection',
      'RootQueryToMediaItemConnection',
      'RootQueryToMenuConnection',
      'RootQueryToMenuItemConnection',
      'RootQueryToOrderConnection',
      'RootQueryToPaBacklightsConnection',
      'RootQueryToPaColorConnection',
      'RootQueryToPageConnection',
      'RootQueryToPaGlubinaConnection',
      'RootQueryToPaShadowGapConnection',
      'RootQueryToPaWidthConnection',
      'RootQueryToPaymentGatewayConnection',
      'RootQueryToPluginConnection',
      'RootQueryToPostConnection',
      'RootQueryToPostFormatConnection',
      'RootQueryToProductCategoryConnection',
      'RootQueryToProductTagConnection',
      'RootQueryToProductTypeConnection',
      'RootQueryToProductUnionConnection',
      'RootQueryToRefundConnection',
      'RootQueryToRevisionsConnection',
      'RootQueryToShippingClassConnection',
      'RootQueryToShippingMethodConnection',
      'RootQueryToShippingZoneConnection',
      'RootQueryToTagConnection',
      'RootQueryToTaxClassConnection',
      'RootQueryToTaxonomyConnection',
      'RootQueryToTaxRateConnection',
      'RootQueryToTermNodeConnection',
      'RootQueryToThemeConnection',
      'RootQueryToUserConnection',
      'RootQueryToUserRoleConnection',
      'RootQueryToVisibleProductConnection',
      'ShippingClassToContentNodeConnection',
      'ShippingClassToProductConnection',
      'ShippingZoneToShippingMethodConnection',
      'SimpleProductToProductUnionConnection',
      'TagToContentNodeConnection',
      'TagToPostConnection',
      'TaxonomyToContentTypeConnection',
      'TaxonomyToTermNodeConnection',
      'TermNodeToEnqueuedScriptConnection',
      'TermNodeToEnqueuedStylesheetConnection',
      'UserToCommentConnection',
      'UserToEnqueuedScriptConnection',
      'UserToEnqueuedStylesheetConnection',
      'UserToMediaItemConnection',
      'UserToPageConnection',
      'UserToPostConnection',
      'UserToRevisionsConnection',
      'UserToUserRoleConnection',
      'VariableProductToProductUnionConnection',
      'VisibleProductToContentNodeConnection',
      'VisibleProductToProductConnection',
    ],
    ContentNode: [
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Page',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    ContentNodeConnection: [
      'CategoryToContentNodeConnection',
      'ContentTypeToContentNodeConnection',
      'HierarchicalContentNodeToContentNodeAncestorsConnection',
      'HierarchicalContentNodeToContentNodeChildrenConnection',
      'PaBacklightsToContentNodeConnection',
      'PaColorToContentNodeConnection',
      'PaGlubinaToContentNodeConnection',
      'PaShadowGapToContentNodeConnection',
      'PaWidthToContentNodeConnection',
      'PostFormatToContentNodeConnection',
      'ProductCategoryToContentNodeConnection',
      'ProductTagToContentNodeConnection',
      'ProductTypeToContentNodeConnection',
      'RootQueryToContentNodeConnection',
      'RootQueryToRevisionsConnection',
      'ShippingClassToContentNodeConnection',
      'TagToContentNodeConnection',
      'UserToRevisionsConnection',
      'VisibleProductToContentNodeConnection',
    ],
    ContentNodeConnectionEdge: [
      'CategoryToContentNodeConnectionEdge',
      'CommentToContentNodeConnectionEdge',
      'ContentTypeToContentNodeConnectionEdge',
      'HierarchicalContentNodeToContentNodeAncestorsConnectionEdge',
      'HierarchicalContentNodeToContentNodeChildrenConnectionEdge',
      'HierarchicalContentNodeToParentContentNodeConnectionEdge',
      'NodeWithRevisionsToContentNodeConnectionEdge',
      'PaBacklightsToContentNodeConnectionEdge',
      'PaColorToContentNodeConnectionEdge',
      'PaGlubinaToContentNodeConnectionEdge',
      'PaShadowGapToContentNodeConnectionEdge',
      'PaWidthToContentNodeConnectionEdge',
      'PostFormatToContentNodeConnectionEdge',
      'ProductCategoryToContentNodeConnectionEdge',
      'ProductTagToContentNodeConnectionEdge',
      'ProductTypeToContentNodeConnectionEdge',
      'RootQueryToContentNodeConnectionEdge',
      'RootQueryToRevisionsConnectionEdge',
      'ShippingClassToContentNodeConnectionEdge',
      'TagToContentNodeConnectionEdge',
      'UserToRevisionsConnectionEdge',
      'VisibleProductToContentNodeConnectionEdge',
    ],
    ContentNodeConnectionPageInfo: [
      'CategoryToContentNodeConnectionPageInfo',
      'ContentTypeToContentNodeConnectionPageInfo',
      'HierarchicalContentNodeToContentNodeAncestorsConnectionPageInfo',
      'HierarchicalContentNodeToContentNodeChildrenConnectionPageInfo',
      'PaBacklightsToContentNodeConnectionPageInfo',
      'PaColorToContentNodeConnectionPageInfo',
      'PaGlubinaToContentNodeConnectionPageInfo',
      'PaShadowGapToContentNodeConnectionPageInfo',
      'PaWidthToContentNodeConnectionPageInfo',
      'PostFormatToContentNodeConnectionPageInfo',
      'ProductCategoryToContentNodeConnectionPageInfo',
      'ProductTagToContentNodeConnectionPageInfo',
      'ProductTypeToContentNodeConnectionPageInfo',
      'RootQueryToContentNodeConnectionPageInfo',
      'RootQueryToRevisionsConnectionPageInfo',
      'ShippingClassToContentNodeConnectionPageInfo',
      'TagToContentNodeConnectionPageInfo',
      'UserToRevisionsConnectionPageInfo',
      'VisibleProductToContentNodeConnectionPageInfo',
    ],
    ContentTemplate: [
      'DefaultTemplate',
      'Template_PageNoTitle',
      'Template_PageWide',
      'Template_PageWithSidebar',
      'Template_SingleWithSidebar',
    ],
    ContentTypeConnection: [
      'RootQueryToContentTypeConnection',
      'TaxonomyToContentTypeConnection',
    ],
    ContentTypeConnectionEdge: [
      'ContentNodeToContentTypeConnectionEdge',
      'RootQueryToContentTypeConnectionEdge',
      'TaxonomyToContentTypeConnectionEdge',
    ],
    ContentTypeConnectionPageInfo: [
      'RootQueryToContentTypeConnectionPageInfo',
      'TaxonomyToContentTypeConnectionPageInfo',
    ],
    CouponConnection: ['RootQueryToCouponConnection'],
    CouponConnectionEdge: ['RootQueryToCouponConnectionEdge'],
    CouponConnectionPageInfo: ['RootQueryToCouponConnectionPageInfo'],
    CouponLineConnection: ['OrderToCouponLineConnection'],
    CouponLineConnectionEdge: ['OrderToCouponLineConnectionEdge'],
    CouponLineConnectionPageInfo: ['OrderToCouponLineConnectionPageInfo'],
    CustomerConnection: [
      'CouponToCustomerConnection',
      'RootQueryToCustomerConnection',
    ],
    CustomerConnectionEdge: [
      'CouponToCustomerConnectionEdge',
      'RootQueryToCustomerConnectionEdge',
    ],
    CustomerConnectionPageInfo: [
      'CouponToCustomerConnectionPageInfo',
      'RootQueryToCustomerConnectionPageInfo',
    ],
    DatabaseIdentifier: [
      'Category',
      'Comment',
      'CommentAuthor',
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Menu',
      'MenuItem',
      'PaBacklights',
      'PaColor',
      'Page',
      'PaGlubina',
      'PaShadowGap',
      'PaWidth',
      'Post',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductType',
      'ShippingClass',
      'SimpleProduct',
      'SimpleProductVariation',
      'Tag',
      'UnsupportedProduct',
      'User',
      'VariableProduct',
      'VisibleProduct',
    ],
    DownloadableItemConnection: [
      'CustomerToDownloadableItemConnection',
      'OrderToDownloadableItemConnection',
    ],
    DownloadableItemConnectionEdge: [
      'CustomerToDownloadableItemConnectionEdge',
      'OrderToDownloadableItemConnectionEdge',
    ],
    DownloadableItemConnectionPageInfo: [
      'CustomerToDownloadableItemConnectionPageInfo',
      'OrderToDownloadableItemConnectionPageInfo',
    ],
    DownloadableProduct: [
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
    ],
    Edge: [
      'CartItemToProductConnectionEdge',
      'CartItemToProductVariationConnectionEdge',
      'CartToCartItemConnectionEdge',
      'CategoryToAncestorsCategoryConnectionEdge',
      'CategoryToCategoryConnectionEdge',
      'CategoryToContentNodeConnectionEdge',
      'CategoryToParentCategoryConnectionEdge',
      'CategoryToPostConnectionEdge',
      'CategoryToTaxonomyConnectionEdge',
      'CommentToCommentConnectionEdge',
      'CommentToCommenterConnectionEdge',
      'CommentToContentNodeConnectionEdge',
      'CommentToParentCommentConnectionEdge',
      'ContentNodeToContentTypeConnectionEdge',
      'ContentNodeToEditLastConnectionEdge',
      'ContentNodeToEditLockConnectionEdge',
      'ContentNodeToEnqueuedScriptConnectionEdge',
      'ContentNodeToEnqueuedStylesheetConnectionEdge',
      'ContentTypeToContentNodeConnectionEdge',
      'ContentTypeToTaxonomyConnectionEdge',
      'CouponToCustomerConnectionEdge',
      'CouponToExcludedProductCategoriesConnectionEdge',
      'CouponToExcludedProductsConnectionEdge',
      'CouponToProductCategoryConnectionEdge',
      'CouponToProductUnionConnectionEdge',
      'CustomerToDownloadableItemConnectionEdge',
      'CustomerToOrderConnectionEdge',
      'CustomerToRefundConnectionEdge',
      'GlobalProductAttributeToTermNodeConnectionEdge',
      'GroupProductToProductUnionConnectionEdge',
      'HierarchicalContentNodeToContentNodeAncestorsConnectionEdge',
      'HierarchicalContentNodeToContentNodeChildrenConnectionEdge',
      'HierarchicalContentNodeToParentContentNodeConnectionEdge',
      'LineItemToProductConnectionEdge',
      'LineItemToProductVariationConnectionEdge',
      'MediaItemToCommentConnectionEdge',
      'MenuItemToMenuConnectionEdge',
      'MenuItemToMenuItemConnectionEdge',
      'MenuItemToMenuItemLinkableConnectionEdge',
      'MenuToMenuItemConnectionEdge',
      'NodeWithAuthorToUserConnectionEdge',
      'NodeWithFeaturedImageToMediaItemConnectionEdge',
      'NodeWithRevisionsToContentNodeConnectionEdge',
      'OrderToCommentConnectionEdge',
      'OrderToCouponLineConnectionEdge',
      'OrderToDownloadableItemConnectionEdge',
      'OrderToFeeLineConnectionEdge',
      'OrderToLineItemConnectionEdge',
      'OrderToRefundConnectionEdge',
      'OrderToShippingLineConnectionEdge',
      'OrderToTaxLineConnectionEdge',
      'PaBacklightsToContentNodeConnectionEdge',
      'PaBacklightsToProductConnectionEdge',
      'PaBacklightsToProductVariationConnectionEdge',
      'PaBacklightsToTaxonomyConnectionEdge',
      'PaColorToContentNodeConnectionEdge',
      'PaColorToProductConnectionEdge',
      'PaColorToProductVariationConnectionEdge',
      'PaColorToTaxonomyConnectionEdge',
      'PageToCommentConnectionEdge',
      'PageToPreviewConnectionEdge',
      'PageToRevisionConnectionEdge',
      'PaGlubinaToContentNodeConnectionEdge',
      'PaGlubinaToProductConnectionEdge',
      'PaGlubinaToProductVariationConnectionEdge',
      'PaGlubinaToTaxonomyConnectionEdge',
      'PaShadowGapToContentNodeConnectionEdge',
      'PaShadowGapToProductConnectionEdge',
      'PaShadowGapToProductVariationConnectionEdge',
      'PaShadowGapToTaxonomyConnectionEdge',
      'PaWidthToContentNodeConnectionEdge',
      'PaWidthToProductConnectionEdge',
      'PaWidthToProductVariationConnectionEdge',
      'PaWidthToTaxonomyConnectionEdge',
      'PostFormatToContentNodeConnectionEdge',
      'PostFormatToPostConnectionEdge',
      'PostFormatToTaxonomyConnectionEdge',
      'PostToCategoryConnectionEdge',
      'PostToCommentConnectionEdge',
      'PostToParentConnectionEdge',
      'PostToPostConnectionEdge',
      'PostToPostFormatConnectionEdge',
      'PostToPreviewConnectionEdge',
      'PostToRevisionConnectionEdge',
      'PostToTagConnectionEdge',
      'PostToTermNodeConnectionEdge',
      'ProductCategoryToAncestorsProductCategoryConnectionEdge',
      'ProductCategoryToContentNodeConnectionEdge',
      'ProductCategoryToParentProductCategoryConnectionEdge',
      'ProductCategoryToProductCategoryConnectionEdge',
      'ProductCategoryToProductConnectionEdge',
      'ProductCategoryToTaxonomyConnectionEdge',
      'ProductTagToContentNodeConnectionEdge',
      'ProductTagToProductConnectionEdge',
      'ProductTagToTaxonomyConnectionEdge',
      'ProductToCommentConnectionEdge',
      'ProductToCommentsConnectionEdge',
      'ProductToGlobalProductAttributeConnectionEdge',
      'ProductToLocalProductAttributeConnectionEdge',
      'ProductToMediaItemConnectionEdge',
      'ProductToPaBacklightsConnectionEdge',
      'ProductToPaColorConnectionEdge',
      'ProductToPaGlubinaConnectionEdge',
      'ProductToPaShadowGapConnectionEdge',
      'ProductToPaWidthConnectionEdge',
      'ProductToProductCategoryConnectionEdge',
      'ProductToProductConnectionEdge',
      'ProductToProductTagConnectionEdge',
      'ProductToProductTypeConnectionEdge',
      'ProductToProductUnionConnectionEdge',
      'ProductToShippingClassConnectionEdge',
      'ProductToTermNodeConnectionEdge',
      'ProductToUpsellConnectionEdge',
      'ProductToVisibleProductConnectionEdge',
      'ProductTypeToContentNodeConnectionEdge',
      'ProductTypeToProductConnectionEdge',
      'ProductTypeToTaxonomyConnectionEdge',
      'ProductVariationToVariationAttributeConnectionEdge',
      'ProductWithAttributesToProductAttributeConnectionEdge',
      'ProductWithAttributesToVariationAttributeConnectionEdge',
      'ProductWithVariationsToProductVariationConnectionEdge',
      'RootQueryToCategoryConnectionEdge',
      'RootQueryToCommentConnectionEdge',
      'RootQueryToContentNodeConnectionEdge',
      'RootQueryToContentTypeConnectionEdge',
      'RootQueryToCouponConnectionEdge',
      'RootQueryToCustomerConnectionEdge',
      'RootQueryToEnqueuedScriptConnectionEdge',
      'RootQueryToEnqueuedStylesheetConnectionEdge',
      'RootQueryToMediaItemConnectionEdge',
      'RootQueryToMenuConnectionEdge',
      'RootQueryToMenuItemConnectionEdge',
      'RootQueryToOrderConnectionEdge',
      'RootQueryToPaBacklightsConnectionEdge',
      'RootQueryToPaColorConnectionEdge',
      'RootQueryToPageConnectionEdge',
      'RootQueryToPaGlubinaConnectionEdge',
      'RootQueryToPaShadowGapConnectionEdge',
      'RootQueryToPaWidthConnectionEdge',
      'RootQueryToPaymentGatewayConnectionEdge',
      'RootQueryToPluginConnectionEdge',
      'RootQueryToPostConnectionEdge',
      'RootQueryToPostFormatConnectionEdge',
      'RootQueryToProductCategoryConnectionEdge',
      'RootQueryToProductTagConnectionEdge',
      'RootQueryToProductTypeConnectionEdge',
      'RootQueryToProductUnionConnectionEdge',
      'RootQueryToRefundConnectionEdge',
      'RootQueryToRevisionsConnectionEdge',
      'RootQueryToShippingClassConnectionEdge',
      'RootQueryToShippingMethodConnectionEdge',
      'RootQueryToShippingZoneConnectionEdge',
      'RootQueryToTagConnectionEdge',
      'RootQueryToTaxClassConnectionEdge',
      'RootQueryToTaxonomyConnectionEdge',
      'RootQueryToTaxRateConnectionEdge',
      'RootQueryToTermNodeConnectionEdge',
      'RootQueryToThemeConnectionEdge',
      'RootQueryToUserConnectionEdge',
      'RootQueryToUserRoleConnectionEdge',
      'RootQueryToVisibleProductConnectionEdge',
      'ShippingClassToContentNodeConnectionEdge',
      'ShippingClassToProductConnectionEdge',
      'ShippingClassToTaxonomyConnectionEdge',
      'ShippingZoneToShippingMethodConnectionEdge',
      'SimpleProductToProductUnionConnectionEdge',
      'TagToContentNodeConnectionEdge',
      'TagToPostConnectionEdge',
      'TagToTaxonomyConnectionEdge',
      'TaxonomyToContentTypeConnectionEdge',
      'TaxonomyToTermNodeConnectionEdge',
      'TermNodeToEnqueuedScriptConnectionEdge',
      'TermNodeToEnqueuedStylesheetConnectionEdge',
      'UserToCommentConnectionEdge',
      'UserToEnqueuedScriptConnectionEdge',
      'UserToEnqueuedStylesheetConnectionEdge',
      'UserToMediaItemConnectionEdge',
      'UserToPageConnectionEdge',
      'UserToPostConnectionEdge',
      'UserToRevisionsConnectionEdge',
      'UserToUserRoleConnectionEdge',
      'VariableProductToProductUnionConnectionEdge',
      'VisibleProductToContentNodeConnectionEdge',
      'VisibleProductToProductConnectionEdge',
      'VisibleProductToTaxonomyConnectionEdge',
    ],
    EnqueuedAsset: ['EnqueuedScript', 'EnqueuedStylesheet'],
    EnqueuedScriptConnection: [
      'ContentNodeToEnqueuedScriptConnection',
      'RootQueryToEnqueuedScriptConnection',
      'TermNodeToEnqueuedScriptConnection',
      'UserToEnqueuedScriptConnection',
    ],
    EnqueuedScriptConnectionEdge: [
      'ContentNodeToEnqueuedScriptConnectionEdge',
      'RootQueryToEnqueuedScriptConnectionEdge',
      'TermNodeToEnqueuedScriptConnectionEdge',
      'UserToEnqueuedScriptConnectionEdge',
    ],
    EnqueuedScriptConnectionPageInfo: [
      'ContentNodeToEnqueuedScriptConnectionPageInfo',
      'RootQueryToEnqueuedScriptConnectionPageInfo',
      'TermNodeToEnqueuedScriptConnectionPageInfo',
      'UserToEnqueuedScriptConnectionPageInfo',
    ],
    EnqueuedStylesheetConnection: [
      'ContentNodeToEnqueuedStylesheetConnection',
      'RootQueryToEnqueuedStylesheetConnection',
      'TermNodeToEnqueuedStylesheetConnection',
      'UserToEnqueuedStylesheetConnection',
    ],
    EnqueuedStylesheetConnectionEdge: [
      'ContentNodeToEnqueuedStylesheetConnectionEdge',
      'RootQueryToEnqueuedStylesheetConnectionEdge',
      'TermNodeToEnqueuedStylesheetConnectionEdge',
      'UserToEnqueuedStylesheetConnectionEdge',
    ],
    EnqueuedStylesheetConnectionPageInfo: [
      'ContentNodeToEnqueuedStylesheetConnectionPageInfo',
      'RootQueryToEnqueuedStylesheetConnectionPageInfo',
      'TermNodeToEnqueuedStylesheetConnectionPageInfo',
      'UserToEnqueuedStylesheetConnectionPageInfo',
    ],
    FeeLineConnection: ['OrderToFeeLineConnection'],
    FeeLineConnectionEdge: ['OrderToFeeLineConnectionEdge'],
    FeeLineConnectionPageInfo: ['OrderToFeeLineConnectionPageInfo'],
    GlobalProductAttributeConnection: [
      'ProductToGlobalProductAttributeConnection',
    ],
    GlobalProductAttributeConnectionEdge: [
      'ProductToGlobalProductAttributeConnectionEdge',
    ],
    GlobalProductAttributeConnectionPageInfo: [
      'ProductToGlobalProductAttributeConnectionPageInfo',
    ],
    HierarchicalContentNode: ['MediaItem', 'Page'],
    HierarchicalNode: ['Category', 'MediaItem', 'Page', 'ProductCategory'],
    HierarchicalTermNode: ['Category', 'ProductCategory'],
    InventoriedProduct: [
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    LineItemConnection: ['OrderToLineItemConnection'],
    LineItemConnectionEdge: ['OrderToLineItemConnectionEdge'],
    LineItemConnectionPageInfo: ['OrderToLineItemConnectionPageInfo'],
    LocalProductAttributeConnection: [
      'ProductToLocalProductAttributeConnection',
    ],
    LocalProductAttributeConnectionEdge: [
      'ProductToLocalProductAttributeConnectionEdge',
    ],
    LocalProductAttributeConnectionPageInfo: [
      'ProductToLocalProductAttributeConnectionPageInfo',
    ],
    MediaItemConnection: [
      'ProductToMediaItemConnection',
      'RootQueryToMediaItemConnection',
      'UserToMediaItemConnection',
    ],
    MediaItemConnectionEdge: [
      'NodeWithFeaturedImageToMediaItemConnectionEdge',
      'ProductToMediaItemConnectionEdge',
      'RootQueryToMediaItemConnectionEdge',
      'UserToMediaItemConnectionEdge',
    ],
    MediaItemConnectionPageInfo: [
      'ProductToMediaItemConnectionPageInfo',
      'RootQueryToMediaItemConnectionPageInfo',
      'UserToMediaItemConnectionPageInfo',
    ],
    MenuConnection: ['RootQueryToMenuConnection'],
    MenuConnectionEdge: [
      'MenuItemToMenuConnectionEdge',
      'RootQueryToMenuConnectionEdge',
    ],
    MenuConnectionPageInfo: ['RootQueryToMenuConnectionPageInfo'],
    MenuItemConnection: [
      'MenuItemToMenuItemConnection',
      'MenuToMenuItemConnection',
      'RootQueryToMenuItemConnection',
    ],
    MenuItemConnectionEdge: [
      'MenuItemToMenuItemConnectionEdge',
      'MenuToMenuItemConnectionEdge',
      'RootQueryToMenuItemConnectionEdge',
    ],
    MenuItemConnectionPageInfo: [
      'MenuItemToMenuItemConnectionPageInfo',
      'MenuToMenuItemConnectionPageInfo',
      'RootQueryToMenuItemConnectionPageInfo',
    ],
    MenuItemLinkable: [
      'Category',
      'ExternalProduct',
      'GroupProduct',
      'Page',
      'Post',
      'ProductCategory',
      'ProductTag',
      'SimpleProduct',
      'SimpleProductVariation',
      'Tag',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    MenuItemLinkableConnectionEdge: [
      'MenuItemToMenuItemLinkableConnectionEdge',
    ],
    MenuItemObjectUnion: [
      'Category',
      'Page',
      'Post',
      'ProductCategory',
      'ProductTag',
      'Tag',
    ],
    Node: [
      'Category',
      'Comment',
      'CommentAuthor',
      'ContentType',
      'Coupon',
      'CouponLine',
      'Customer',
      'DownloadableItem',
      'EnqueuedScript',
      'EnqueuedStylesheet',
      'ExternalProduct',
      'FeeLine',
      'GlobalProductAttribute',
      'GroupProduct',
      'LineItem',
      'LocalProductAttribute',
      'MediaItem',
      'Menu',
      'MenuItem',
      'Order',
      'PaBacklights',
      'PaColor',
      'Page',
      'PaGlubina',
      'PaShadowGap',
      'PaWidth',
      'PaymentGateway',
      'PaymentTokenCC',
      'PaymentTokenECheck',
      'Plugin',
      'Post',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductType',
      'Refund',
      'ShippingClass',
      'ShippingLine',
      'ShippingMethod',
      'ShippingZone',
      'SimpleAttribute',
      'SimpleCartItem',
      'SimpleProduct',
      'SimpleProductVariation',
      'Tag',
      'TaxClass',
      'TaxLine',
      'Taxonomy',
      'TaxRate',
      'Theme',
      'UnsupportedProduct',
      'User',
      'UserRole',
      'VariableProduct',
      'VariationAttribute',
      'VisibleProduct',
    ],
    NodeWithAuthor: ['MediaItem', 'Page', 'Post'],
    NodeWithComments: [
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Order',
      'Page',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    NodeWithContentEditor: [
      'ExternalProduct',
      'GroupProduct',
      'Page',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    NodeWithExcerpt: [
      'ExternalProduct',
      'GroupProduct',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    NodeWithFeaturedImage: [
      'ExternalProduct',
      'GroupProduct',
      'Page',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    NodeWithPageAttributes: ['Page'],
    NodeWithRevisions: ['Page', 'Post'],
    NodeWithTemplate: [
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Page',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    NodeWithTitle: [
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'Page',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    NodeWithTrackbacks: ['Post'],
    OneToOneConnection: [
      'CartItemToProductConnectionEdge',
      'CartItemToProductVariationConnectionEdge',
      'CategoryToParentCategoryConnectionEdge',
      'CategoryToTaxonomyConnectionEdge',
      'CommentToCommenterConnectionEdge',
      'CommentToContentNodeConnectionEdge',
      'CommentToParentCommentConnectionEdge',
      'ContentNodeToContentTypeConnectionEdge',
      'ContentNodeToEditLastConnectionEdge',
      'ContentNodeToEditLockConnectionEdge',
      'HierarchicalContentNodeToParentContentNodeConnectionEdge',
      'LineItemToProductConnectionEdge',
      'LineItemToProductVariationConnectionEdge',
      'MenuItemToMenuConnectionEdge',
      'MenuItemToMenuItemLinkableConnectionEdge',
      'NodeWithAuthorToUserConnectionEdge',
      'NodeWithFeaturedImageToMediaItemConnectionEdge',
      'NodeWithRevisionsToContentNodeConnectionEdge',
      'PaBacklightsToTaxonomyConnectionEdge',
      'PaColorToTaxonomyConnectionEdge',
      'PageToPreviewConnectionEdge',
      'PaGlubinaToTaxonomyConnectionEdge',
      'PaShadowGapToTaxonomyConnectionEdge',
      'PaWidthToTaxonomyConnectionEdge',
      'PostFormatToTaxonomyConnectionEdge',
      'PostToParentConnectionEdge',
      'PostToPreviewConnectionEdge',
      'ProductCategoryToParentProductCategoryConnectionEdge',
      'ProductCategoryToTaxonomyConnectionEdge',
      'ProductTagToTaxonomyConnectionEdge',
      'ProductToProductConnectionEdge',
      'ProductTypeToTaxonomyConnectionEdge',
      'ShippingClassToTaxonomyConnectionEdge',
      'TagToTaxonomyConnectionEdge',
      'VisibleProductToTaxonomyConnectionEdge',
    ],
    OrderConnection: [
      'CustomerToOrderConnection',
      'RootQueryToOrderConnection',
    ],
    OrderConnectionEdge: [
      'CustomerToOrderConnectionEdge',
      'RootQueryToOrderConnectionEdge',
    ],
    OrderConnectionPageInfo: [
      'CustomerToOrderConnectionPageInfo',
      'RootQueryToOrderConnectionPageInfo',
    ],
    PaBacklightsConnection: [
      'ProductToPaBacklightsConnection',
      'RootQueryToPaBacklightsConnection',
    ],
    PaBacklightsConnectionEdge: [
      'ProductToPaBacklightsConnectionEdge',
      'RootQueryToPaBacklightsConnectionEdge',
    ],
    PaBacklightsConnectionPageInfo: [
      'ProductToPaBacklightsConnectionPageInfo',
      'RootQueryToPaBacklightsConnectionPageInfo',
    ],
    PaColorConnection: [
      'ProductToPaColorConnection',
      'RootQueryToPaColorConnection',
    ],
    PaColorConnectionEdge: [
      'ProductToPaColorConnectionEdge',
      'RootQueryToPaColorConnectionEdge',
    ],
    PaColorConnectionPageInfo: [
      'ProductToPaColorConnectionPageInfo',
      'RootQueryToPaColorConnectionPageInfo',
    ],
    PageConnection: [
      'PageToRevisionConnection',
      'RootQueryToPageConnection',
      'UserToPageConnection',
    ],
    PageConnectionEdge: [
      'PageToPreviewConnectionEdge',
      'PageToRevisionConnectionEdge',
      'RootQueryToPageConnectionEdge',
      'UserToPageConnectionEdge',
    ],
    PageConnectionPageInfo: [
      'PageToRevisionConnectionPageInfo',
      'RootQueryToPageConnectionPageInfo',
      'UserToPageConnectionPageInfo',
    ],
    PageInfo: [
      'CartToCartItemConnectionPageInfo',
      'CategoryToAncestorsCategoryConnectionPageInfo',
      'CategoryToCategoryConnectionPageInfo',
      'CategoryToContentNodeConnectionPageInfo',
      'CategoryToPostConnectionPageInfo',
      'CommentToCommentConnectionPageInfo',
      'ContentNodeToEnqueuedScriptConnectionPageInfo',
      'ContentNodeToEnqueuedStylesheetConnectionPageInfo',
      'ContentTypeToContentNodeConnectionPageInfo',
      'ContentTypeToTaxonomyConnectionPageInfo',
      'CouponToCustomerConnectionPageInfo',
      'CouponToExcludedProductCategoriesConnectionPageInfo',
      'CouponToExcludedProductsConnectionPageInfo',
      'CouponToProductCategoryConnectionPageInfo',
      'CouponToProductUnionConnectionPageInfo',
      'CustomerToDownloadableItemConnectionPageInfo',
      'CustomerToOrderConnectionPageInfo',
      'CustomerToRefundConnectionPageInfo',
      'GlobalProductAttributeToTermNodeConnectionPageInfo',
      'GroupProductToProductUnionConnectionPageInfo',
      'HierarchicalContentNodeToContentNodeAncestorsConnectionPageInfo',
      'HierarchicalContentNodeToContentNodeChildrenConnectionPageInfo',
      'MediaItemToCommentConnectionPageInfo',
      'MenuItemToMenuItemConnectionPageInfo',
      'MenuToMenuItemConnectionPageInfo',
      'OrderToCommentConnectionPageInfo',
      'OrderToCouponLineConnectionPageInfo',
      'OrderToDownloadableItemConnectionPageInfo',
      'OrderToFeeLineConnectionPageInfo',
      'OrderToLineItemConnectionPageInfo',
      'OrderToRefundConnectionPageInfo',
      'OrderToShippingLineConnectionPageInfo',
      'OrderToTaxLineConnectionPageInfo',
      'PaBacklightsToContentNodeConnectionPageInfo',
      'PaBacklightsToProductConnectionPageInfo',
      'PaBacklightsToProductVariationConnectionPageInfo',
      'PaColorToContentNodeConnectionPageInfo',
      'PaColorToProductConnectionPageInfo',
      'PaColorToProductVariationConnectionPageInfo',
      'PageToCommentConnectionPageInfo',
      'PageToRevisionConnectionPageInfo',
      'PaGlubinaToContentNodeConnectionPageInfo',
      'PaGlubinaToProductConnectionPageInfo',
      'PaGlubinaToProductVariationConnectionPageInfo',
      'PaShadowGapToContentNodeConnectionPageInfo',
      'PaShadowGapToProductConnectionPageInfo',
      'PaShadowGapToProductVariationConnectionPageInfo',
      'PaWidthToContentNodeConnectionPageInfo',
      'PaWidthToProductConnectionPageInfo',
      'PaWidthToProductVariationConnectionPageInfo',
      'PostFormatToContentNodeConnectionPageInfo',
      'PostFormatToPostConnectionPageInfo',
      'PostToCategoryConnectionPageInfo',
      'PostToCommentConnectionPageInfo',
      'PostToPostConnectionPageInfo',
      'PostToPostFormatConnectionPageInfo',
      'PostToRevisionConnectionPageInfo',
      'PostToTagConnectionPageInfo',
      'PostToTermNodeConnectionPageInfo',
      'ProductCategoryToAncestorsProductCategoryConnectionPageInfo',
      'ProductCategoryToContentNodeConnectionPageInfo',
      'ProductCategoryToProductCategoryConnectionPageInfo',
      'ProductCategoryToProductConnectionPageInfo',
      'ProductTagToContentNodeConnectionPageInfo',
      'ProductTagToProductConnectionPageInfo',
      'ProductToCommentConnectionPageInfo',
      'ProductToCommentsConnectionPageInfo',
      'ProductToGlobalProductAttributeConnectionPageInfo',
      'ProductToLocalProductAttributeConnectionPageInfo',
      'ProductToMediaItemConnectionPageInfo',
      'ProductToPaBacklightsConnectionPageInfo',
      'ProductToPaColorConnectionPageInfo',
      'ProductToPaGlubinaConnectionPageInfo',
      'ProductToPaShadowGapConnectionPageInfo',
      'ProductToPaWidthConnectionPageInfo',
      'ProductToProductCategoryConnectionPageInfo',
      'ProductToProductTagConnectionPageInfo',
      'ProductToProductTypeConnectionPageInfo',
      'ProductToProductUnionConnectionPageInfo',
      'ProductToShippingClassConnectionPageInfo',
      'ProductToTermNodeConnectionPageInfo',
      'ProductToUpsellConnectionPageInfo',
      'ProductToVisibleProductConnectionPageInfo',
      'ProductTypeToContentNodeConnectionPageInfo',
      'ProductTypeToProductConnectionPageInfo',
      'ProductVariationToVariationAttributeConnectionPageInfo',
      'ProductWithAttributesToProductAttributeConnectionPageInfo',
      'ProductWithAttributesToVariationAttributeConnectionPageInfo',
      'ProductWithVariationsToProductVariationConnectionPageInfo',
      'RootQueryToCategoryConnectionPageInfo',
      'RootQueryToCommentConnectionPageInfo',
      'RootQueryToContentNodeConnectionPageInfo',
      'RootQueryToContentTypeConnectionPageInfo',
      'RootQueryToCouponConnectionPageInfo',
      'RootQueryToCustomerConnectionPageInfo',
      'RootQueryToEnqueuedScriptConnectionPageInfo',
      'RootQueryToEnqueuedStylesheetConnectionPageInfo',
      'RootQueryToMediaItemConnectionPageInfo',
      'RootQueryToMenuConnectionPageInfo',
      'RootQueryToMenuItemConnectionPageInfo',
      'RootQueryToOrderConnectionPageInfo',
      'RootQueryToPaBacklightsConnectionPageInfo',
      'RootQueryToPaColorConnectionPageInfo',
      'RootQueryToPageConnectionPageInfo',
      'RootQueryToPaGlubinaConnectionPageInfo',
      'RootQueryToPaShadowGapConnectionPageInfo',
      'RootQueryToPaWidthConnectionPageInfo',
      'RootQueryToPaymentGatewayConnectionPageInfo',
      'RootQueryToPluginConnectionPageInfo',
      'RootQueryToPostConnectionPageInfo',
      'RootQueryToPostFormatConnectionPageInfo',
      'RootQueryToProductCategoryConnectionPageInfo',
      'RootQueryToProductTagConnectionPageInfo',
      'RootQueryToProductTypeConnectionPageInfo',
      'RootQueryToProductUnionConnectionPageInfo',
      'RootQueryToRefundConnectionPageInfo',
      'RootQueryToRevisionsConnectionPageInfo',
      'RootQueryToShippingClassConnectionPageInfo',
      'RootQueryToShippingMethodConnectionPageInfo',
      'RootQueryToShippingZoneConnectionPageInfo',
      'RootQueryToTagConnectionPageInfo',
      'RootQueryToTaxClassConnectionPageInfo',
      'RootQueryToTaxonomyConnectionPageInfo',
      'RootQueryToTaxRateConnectionPageInfo',
      'RootQueryToTermNodeConnectionPageInfo',
      'RootQueryToThemeConnectionPageInfo',
      'RootQueryToUserConnectionPageInfo',
      'RootQueryToUserRoleConnectionPageInfo',
      'RootQueryToVisibleProductConnectionPageInfo',
      'ShippingClassToContentNodeConnectionPageInfo',
      'ShippingClassToProductConnectionPageInfo',
      'ShippingZoneToShippingMethodConnectionPageInfo',
      'SimpleProductToProductUnionConnectionPageInfo',
      'TagToContentNodeConnectionPageInfo',
      'TagToPostConnectionPageInfo',
      'TaxonomyToContentTypeConnectionPageInfo',
      'TaxonomyToTermNodeConnectionPageInfo',
      'TermNodeToEnqueuedScriptConnectionPageInfo',
      'TermNodeToEnqueuedStylesheetConnectionPageInfo',
      'UserToCommentConnectionPageInfo',
      'UserToEnqueuedScriptConnectionPageInfo',
      'UserToEnqueuedStylesheetConnectionPageInfo',
      'UserToMediaItemConnectionPageInfo',
      'UserToPageConnectionPageInfo',
      'UserToPostConnectionPageInfo',
      'UserToRevisionsConnectionPageInfo',
      'UserToUserRoleConnectionPageInfo',
      'VariableProductToProductUnionConnectionPageInfo',
      'VisibleProductToContentNodeConnectionPageInfo',
      'VisibleProductToProductConnectionPageInfo',
    ],
    PaGlubinaConnection: [
      'ProductToPaGlubinaConnection',
      'RootQueryToPaGlubinaConnection',
    ],
    PaGlubinaConnectionEdge: [
      'ProductToPaGlubinaConnectionEdge',
      'RootQueryToPaGlubinaConnectionEdge',
    ],
    PaGlubinaConnectionPageInfo: [
      'ProductToPaGlubinaConnectionPageInfo',
      'RootQueryToPaGlubinaConnectionPageInfo',
    ],
    PaShadowGapConnection: [
      'ProductToPaShadowGapConnection',
      'RootQueryToPaShadowGapConnection',
    ],
    PaShadowGapConnectionEdge: [
      'ProductToPaShadowGapConnectionEdge',
      'RootQueryToPaShadowGapConnectionEdge',
    ],
    PaShadowGapConnectionPageInfo: [
      'ProductToPaShadowGapConnectionPageInfo',
      'RootQueryToPaShadowGapConnectionPageInfo',
    ],
    PaWidthConnection: [
      'ProductToPaWidthConnection',
      'RootQueryToPaWidthConnection',
    ],
    PaWidthConnectionEdge: [
      'ProductToPaWidthConnectionEdge',
      'RootQueryToPaWidthConnectionEdge',
    ],
    PaWidthConnectionPageInfo: [
      'ProductToPaWidthConnectionPageInfo',
      'RootQueryToPaWidthConnectionPageInfo',
    ],
    PaymentGatewayConnection: ['RootQueryToPaymentGatewayConnection'],
    PaymentGatewayConnectionEdge: ['RootQueryToPaymentGatewayConnectionEdge'],
    PaymentGatewayConnectionPageInfo: [
      'RootQueryToPaymentGatewayConnectionPageInfo',
    ],
    PaymentToken: ['PaymentTokenCC', 'PaymentTokenECheck'],
    PluginConnection: ['RootQueryToPluginConnection'],
    PluginConnectionEdge: ['RootQueryToPluginConnectionEdge'],
    PluginConnectionPageInfo: ['RootQueryToPluginConnectionPageInfo'],
    PostConnection: [
      'CategoryToPostConnection',
      'PostFormatToPostConnection',
      'PostToPostConnection',
      'PostToRevisionConnection',
      'RootQueryToPostConnection',
      'TagToPostConnection',
      'UserToPostConnection',
    ],
    PostConnectionEdge: [
      'CategoryToPostConnectionEdge',
      'PostFormatToPostConnectionEdge',
      'PostToParentConnectionEdge',
      'PostToPostConnectionEdge',
      'PostToPreviewConnectionEdge',
      'PostToRevisionConnectionEdge',
      'RootQueryToPostConnectionEdge',
      'TagToPostConnectionEdge',
      'UserToPostConnectionEdge',
    ],
    PostConnectionPageInfo: [
      'CategoryToPostConnectionPageInfo',
      'PostFormatToPostConnectionPageInfo',
      'PostToPostConnectionPageInfo',
      'PostToRevisionConnectionPageInfo',
      'RootQueryToPostConnectionPageInfo',
      'TagToPostConnectionPageInfo',
      'UserToPostConnectionPageInfo',
    ],
    PostFormatConnection: [
      'PostToPostFormatConnection',
      'RootQueryToPostFormatConnection',
    ],
    PostFormatConnectionEdge: [
      'PostToPostFormatConnectionEdge',
      'RootQueryToPostFormatConnectionEdge',
    ],
    PostFormatConnectionPageInfo: [
      'PostToPostFormatConnectionPageInfo',
      'RootQueryToPostFormatConnectionPageInfo',
    ],
    Previewable: [
      'ExternalProduct',
      'GroupProduct',
      'Page',
      'Post',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    Product: [
      'ExternalProduct',
      'GroupProduct',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    ProductAttribute: ['GlobalProductAttribute', 'LocalProductAttribute'],
    ProductAttributeConnection: [
      'ProductWithAttributesToProductAttributeConnection',
    ],
    ProductAttributeConnectionEdge: [
      'ProductWithAttributesToProductAttributeConnectionEdge',
    ],
    ProductAttributeConnectionPageInfo: [
      'ProductWithAttributesToProductAttributeConnectionPageInfo',
    ],
    ProductCategoryConnection: [
      'CouponToExcludedProductCategoriesConnection',
      'CouponToProductCategoryConnection',
      'ProductCategoryToAncestorsProductCategoryConnection',
      'ProductCategoryToProductCategoryConnection',
      'ProductToProductCategoryConnection',
      'RootQueryToProductCategoryConnection',
    ],
    ProductCategoryConnectionEdge: [
      'CouponToExcludedProductCategoriesConnectionEdge',
      'CouponToProductCategoryConnectionEdge',
      'ProductCategoryToAncestorsProductCategoryConnectionEdge',
      'ProductCategoryToParentProductCategoryConnectionEdge',
      'ProductCategoryToProductCategoryConnectionEdge',
      'ProductToProductCategoryConnectionEdge',
      'RootQueryToProductCategoryConnectionEdge',
    ],
    ProductCategoryConnectionPageInfo: [
      'CouponToExcludedProductCategoriesConnectionPageInfo',
      'CouponToProductCategoryConnectionPageInfo',
      'ProductCategoryToAncestorsProductCategoryConnectionPageInfo',
      'ProductCategoryToProductCategoryConnectionPageInfo',
      'ProductToProductCategoryConnectionPageInfo',
      'RootQueryToProductCategoryConnectionPageInfo',
    ],
    ProductConnection: [
      'PaBacklightsToProductConnection',
      'PaColorToProductConnection',
      'PaGlubinaToProductConnection',
      'PaShadowGapToProductConnection',
      'PaWidthToProductConnection',
      'ProductCategoryToProductConnection',
      'ProductTagToProductConnection',
      'ProductTypeToProductConnection',
      'ShippingClassToProductConnection',
      'VisibleProductToProductConnection',
    ],
    ProductConnectionEdge: [
      'CartItemToProductConnectionEdge',
      'LineItemToProductConnectionEdge',
      'PaBacklightsToProductConnectionEdge',
      'PaColorToProductConnectionEdge',
      'PaGlubinaToProductConnectionEdge',
      'PaShadowGapToProductConnectionEdge',
      'PaWidthToProductConnectionEdge',
      'ProductCategoryToProductConnectionEdge',
      'ProductTagToProductConnectionEdge',
      'ProductToProductConnectionEdge',
      'ProductTypeToProductConnectionEdge',
      'ShippingClassToProductConnectionEdge',
      'VisibleProductToProductConnectionEdge',
    ],
    ProductConnectionPageInfo: [
      'PaBacklightsToProductConnectionPageInfo',
      'PaColorToProductConnectionPageInfo',
      'PaGlubinaToProductConnectionPageInfo',
      'PaShadowGapToProductConnectionPageInfo',
      'PaWidthToProductConnectionPageInfo',
      'ProductCategoryToProductConnectionPageInfo',
      'ProductTagToProductConnectionPageInfo',
      'ProductTypeToProductConnectionPageInfo',
      'ShippingClassToProductConnectionPageInfo',
      'VisibleProductToProductConnectionPageInfo',
    ],
    ProductTagConnection: [
      'ProductToProductTagConnection',
      'RootQueryToProductTagConnection',
    ],
    ProductTagConnectionEdge: [
      'ProductToProductTagConnectionEdge',
      'RootQueryToProductTagConnectionEdge',
    ],
    ProductTagConnectionPageInfo: [
      'ProductToProductTagConnectionPageInfo',
      'RootQueryToProductTagConnectionPageInfo',
    ],
    ProductTypeConnection: [
      'ProductToProductTypeConnection',
      'RootQueryToProductTypeConnection',
    ],
    ProductTypeConnectionEdge: [
      'ProductToProductTypeConnectionEdge',
      'RootQueryToProductTypeConnectionEdge',
    ],
    ProductTypeConnectionPageInfo: [
      'ProductToProductTypeConnectionPageInfo',
      'RootQueryToProductTypeConnectionPageInfo',
    ],
    ProductUnion: [
      'ExternalProduct',
      'GroupProduct',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    ProductUnionConnection: [
      'CouponToExcludedProductsConnection',
      'CouponToProductUnionConnection',
      'GroupProductToProductUnionConnection',
      'ProductToProductUnionConnection',
      'ProductToUpsellConnection',
      'RootQueryToProductUnionConnection',
      'SimpleProductToProductUnionConnection',
      'VariableProductToProductUnionConnection',
    ],
    ProductUnionConnectionEdge: [
      'CouponToExcludedProductsConnectionEdge',
      'CouponToProductUnionConnectionEdge',
      'GroupProductToProductUnionConnectionEdge',
      'ProductToProductUnionConnectionEdge',
      'ProductToUpsellConnectionEdge',
      'RootQueryToProductUnionConnectionEdge',
      'SimpleProductToProductUnionConnectionEdge',
      'VariableProductToProductUnionConnectionEdge',
    ],
    ProductUnionConnectionPageInfo: [
      'CouponToExcludedProductsConnectionPageInfo',
      'CouponToProductUnionConnectionPageInfo',
      'GroupProductToProductUnionConnectionPageInfo',
      'ProductToProductUnionConnectionPageInfo',
      'ProductToUpsellConnectionPageInfo',
      'RootQueryToProductUnionConnectionPageInfo',
      'SimpleProductToProductUnionConnectionPageInfo',
      'VariableProductToProductUnionConnectionPageInfo',
    ],
    ProductVariation: ['SimpleProductVariation'],
    ProductVariationConnection: [
      'PaBacklightsToProductVariationConnection',
      'PaColorToProductVariationConnection',
      'PaGlubinaToProductVariationConnection',
      'PaShadowGapToProductVariationConnection',
      'PaWidthToProductVariationConnection',
      'ProductWithVariationsToProductVariationConnection',
    ],
    ProductVariationConnectionEdge: [
      'CartItemToProductVariationConnectionEdge',
      'LineItemToProductVariationConnectionEdge',
      'PaBacklightsToProductVariationConnectionEdge',
      'PaColorToProductVariationConnectionEdge',
      'PaGlubinaToProductVariationConnectionEdge',
      'PaShadowGapToProductVariationConnectionEdge',
      'PaWidthToProductVariationConnectionEdge',
      'ProductWithVariationsToProductVariationConnectionEdge',
    ],
    ProductVariationConnectionPageInfo: [
      'PaBacklightsToProductVariationConnectionPageInfo',
      'PaColorToProductVariationConnectionPageInfo',
      'PaGlubinaToProductVariationConnectionPageInfo',
      'PaShadowGapToProductVariationConnectionPageInfo',
      'PaWidthToProductVariationConnectionPageInfo',
      'ProductWithVariationsToProductVariationConnectionPageInfo',
    ],
    ProductWithAttributes: [
      'ExternalProduct',
      'GroupProduct',
      'SimpleProduct',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    ProductWithDimensions: [
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    ProductWithPricing: [
      'ExternalProduct',
      'GroupProduct',
      'SimpleProduct',
      'SimpleProductVariation',
      'UnsupportedProduct',
      'VariableProduct',
    ],
    ProductWithVariations: ['VariableProduct'],
    RefundConnection: [
      'CustomerToRefundConnection',
      'OrderToRefundConnection',
      'RootQueryToRefundConnection',
    ],
    RefundConnectionEdge: [
      'CustomerToRefundConnectionEdge',
      'OrderToRefundConnectionEdge',
      'RootQueryToRefundConnectionEdge',
    ],
    RefundConnectionPageInfo: [
      'CustomerToRefundConnectionPageInfo',
      'OrderToRefundConnectionPageInfo',
      'RootQueryToRefundConnectionPageInfo',
    ],
    ShippingClassConnection: [
      'ProductToShippingClassConnection',
      'RootQueryToShippingClassConnection',
    ],
    ShippingClassConnectionEdge: [
      'ProductToShippingClassConnectionEdge',
      'RootQueryToShippingClassConnectionEdge',
    ],
    ShippingClassConnectionPageInfo: [
      'ProductToShippingClassConnectionPageInfo',
      'RootQueryToShippingClassConnectionPageInfo',
    ],
    ShippingLineConnection: ['OrderToShippingLineConnection'],
    ShippingLineConnectionEdge: ['OrderToShippingLineConnectionEdge'],
    ShippingLineConnectionPageInfo: ['OrderToShippingLineConnectionPageInfo'],
    ShippingMethodConnection: [
      'RootQueryToShippingMethodConnection',
      'ShippingZoneToShippingMethodConnection',
    ],
    ShippingMethodConnectionEdge: [
      'RootQueryToShippingMethodConnectionEdge',
      'ShippingZoneToShippingMethodConnectionEdge',
    ],
    ShippingMethodConnectionPageInfo: [
      'RootQueryToShippingMethodConnectionPageInfo',
      'ShippingZoneToShippingMethodConnectionPageInfo',
    ],
    ShippingZoneConnection: ['RootQueryToShippingZoneConnection'],
    ShippingZoneConnectionEdge: ['RootQueryToShippingZoneConnectionEdge'],
    ShippingZoneConnectionPageInfo: [
      'RootQueryToShippingZoneConnectionPageInfo',
    ],
    TagConnection: ['PostToTagConnection', 'RootQueryToTagConnection'],
    TagConnectionEdge: [
      'PostToTagConnectionEdge',
      'RootQueryToTagConnectionEdge',
    ],
    TagConnectionPageInfo: [
      'PostToTagConnectionPageInfo',
      'RootQueryToTagConnectionPageInfo',
    ],
    TaxClassConnection: ['RootQueryToTaxClassConnection'],
    TaxClassConnectionEdge: ['RootQueryToTaxClassConnectionEdge'],
    TaxClassConnectionPageInfo: ['RootQueryToTaxClassConnectionPageInfo'],
    TaxLineConnection: ['OrderToTaxLineConnection'],
    TaxLineConnectionEdge: ['OrderToTaxLineConnectionEdge'],
    TaxLineConnectionPageInfo: ['OrderToTaxLineConnectionPageInfo'],
    TaxonomyConnection: [
      'ContentTypeToTaxonomyConnection',
      'RootQueryToTaxonomyConnection',
    ],
    TaxonomyConnectionEdge: [
      'CategoryToTaxonomyConnectionEdge',
      'ContentTypeToTaxonomyConnectionEdge',
      'PaBacklightsToTaxonomyConnectionEdge',
      'PaColorToTaxonomyConnectionEdge',
      'PaGlubinaToTaxonomyConnectionEdge',
      'PaShadowGapToTaxonomyConnectionEdge',
      'PaWidthToTaxonomyConnectionEdge',
      'PostFormatToTaxonomyConnectionEdge',
      'ProductCategoryToTaxonomyConnectionEdge',
      'ProductTagToTaxonomyConnectionEdge',
      'ProductTypeToTaxonomyConnectionEdge',
      'RootQueryToTaxonomyConnectionEdge',
      'ShippingClassToTaxonomyConnectionEdge',
      'TagToTaxonomyConnectionEdge',
      'VisibleProductToTaxonomyConnectionEdge',
    ],
    TaxonomyConnectionPageInfo: [
      'ContentTypeToTaxonomyConnectionPageInfo',
      'RootQueryToTaxonomyConnectionPageInfo',
    ],
    TaxRateConnection: ['RootQueryToTaxRateConnection'],
    TaxRateConnectionEdge: ['RootQueryToTaxRateConnectionEdge'],
    TaxRateConnectionPageInfo: ['RootQueryToTaxRateConnectionPageInfo'],
    TermNode: [
      'Category',
      'PaBacklights',
      'PaColor',
      'PaGlubina',
      'PaShadowGap',
      'PaWidth',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductType',
      'ShippingClass',
      'Tag',
      'VisibleProduct',
    ],
    TermNodeConnection: [
      'GlobalProductAttributeToTermNodeConnection',
      'PostToTermNodeConnection',
      'ProductToTermNodeConnection',
      'RootQueryToTermNodeConnection',
      'TaxonomyToTermNodeConnection',
    ],
    TermNodeConnectionEdge: [
      'GlobalProductAttributeToTermNodeConnectionEdge',
      'PostToTermNodeConnectionEdge',
      'ProductToTermNodeConnectionEdge',
      'RootQueryToTermNodeConnectionEdge',
      'TaxonomyToTermNodeConnectionEdge',
    ],
    TermNodeConnectionPageInfo: [
      'GlobalProductAttributeToTermNodeConnectionPageInfo',
      'PostToTermNodeConnectionPageInfo',
      'ProductToTermNodeConnectionPageInfo',
      'RootQueryToTermNodeConnectionPageInfo',
      'TaxonomyToTermNodeConnectionPageInfo',
    ],
    ThemeConnection: ['RootQueryToThemeConnection'],
    ThemeConnectionEdge: ['RootQueryToThemeConnectionEdge'],
    ThemeConnectionPageInfo: ['RootQueryToThemeConnectionPageInfo'],
    UniformResourceIdentifiable: [
      'Category',
      'Comment',
      'ContentType',
      'ExternalProduct',
      'GroupProduct',
      'MediaItem',
      'PaBacklights',
      'PaColor',
      'Page',
      'PaGlubina',
      'PaShadowGap',
      'PaWidth',
      'Post',
      'PostFormat',
      'ProductCategory',
      'ProductTag',
      'ProductType',
      'ShippingClass',
      'SimpleProduct',
      'SimpleProductVariation',
      'Tag',
      'UnsupportedProduct',
      'User',
      'VariableProduct',
      'VisibleProduct',
    ],
    UserConnection: ['RootQueryToUserConnection'],
    UserConnectionEdge: [
      'ContentNodeToEditLastConnectionEdge',
      'ContentNodeToEditLockConnectionEdge',
      'NodeWithAuthorToUserConnectionEdge',
      'RootQueryToUserConnectionEdge',
    ],
    UserConnectionPageInfo: ['RootQueryToUserConnectionPageInfo'],
    UserRoleConnection: [
      'RootQueryToUserRoleConnection',
      'UserToUserRoleConnection',
    ],
    UserRoleConnectionEdge: [
      'RootQueryToUserRoleConnectionEdge',
      'UserToUserRoleConnectionEdge',
    ],
    UserRoleConnectionPageInfo: [
      'RootQueryToUserRoleConnectionPageInfo',
      'UserToUserRoleConnectionPageInfo',
    ],
    VariationAttributeConnection: [
      'ProductVariationToVariationAttributeConnection',
      'ProductWithAttributesToVariationAttributeConnection',
    ],
    VariationAttributeConnectionEdge: [
      'ProductVariationToVariationAttributeConnectionEdge',
      'ProductWithAttributesToVariationAttributeConnectionEdge',
    ],
    VariationAttributeConnectionPageInfo: [
      'ProductVariationToVariationAttributeConnectionPageInfo',
      'ProductWithAttributesToVariationAttributeConnectionPageInfo',
    ],
    VisibleProductConnection: [
      'ProductToVisibleProductConnection',
      'RootQueryToVisibleProductConnection',
    ],
    VisibleProductConnectionEdge: [
      'ProductToVisibleProductConnectionEdge',
      'RootQueryToVisibleProductConnectionEdge',
    ],
    VisibleProductConnectionPageInfo: [
      'ProductToVisibleProductConnectionPageInfo',
      'RootQueryToVisibleProductConnectionPageInfo',
    ],
    WPPageInfo: [
      'CartToCartItemConnectionPageInfo',
      'CategoryToAncestorsCategoryConnectionPageInfo',
      'CategoryToCategoryConnectionPageInfo',
      'CategoryToContentNodeConnectionPageInfo',
      'CategoryToPostConnectionPageInfo',
      'CommentToCommentConnectionPageInfo',
      'ContentNodeToEnqueuedScriptConnectionPageInfo',
      'ContentNodeToEnqueuedStylesheetConnectionPageInfo',
      'ContentTypeToContentNodeConnectionPageInfo',
      'ContentTypeToTaxonomyConnectionPageInfo',
      'CouponToCustomerConnectionPageInfo',
      'CouponToExcludedProductCategoriesConnectionPageInfo',
      'CouponToExcludedProductsConnectionPageInfo',
      'CouponToProductCategoryConnectionPageInfo',
      'CouponToProductUnionConnectionPageInfo',
      'CustomerToDownloadableItemConnectionPageInfo',
      'CustomerToOrderConnectionPageInfo',
      'CustomerToRefundConnectionPageInfo',
      'GlobalProductAttributeToTermNodeConnectionPageInfo',
      'GroupProductToProductUnionConnectionPageInfo',
      'HierarchicalContentNodeToContentNodeAncestorsConnectionPageInfo',
      'HierarchicalContentNodeToContentNodeChildrenConnectionPageInfo',
      'MediaItemToCommentConnectionPageInfo',
      'MenuItemToMenuItemConnectionPageInfo',
      'MenuToMenuItemConnectionPageInfo',
      'OrderToCommentConnectionPageInfo',
      'OrderToCouponLineConnectionPageInfo',
      'OrderToDownloadableItemConnectionPageInfo',
      'OrderToFeeLineConnectionPageInfo',
      'OrderToLineItemConnectionPageInfo',
      'OrderToRefundConnectionPageInfo',
      'OrderToShippingLineConnectionPageInfo',
      'OrderToTaxLineConnectionPageInfo',
      'PaBacklightsToContentNodeConnectionPageInfo',
      'PaBacklightsToProductConnectionPageInfo',
      'PaBacklightsToProductVariationConnectionPageInfo',
      'PaColorToContentNodeConnectionPageInfo',
      'PaColorToProductConnectionPageInfo',
      'PaColorToProductVariationConnectionPageInfo',
      'PageToCommentConnectionPageInfo',
      'PageToRevisionConnectionPageInfo',
      'PaGlubinaToContentNodeConnectionPageInfo',
      'PaGlubinaToProductConnectionPageInfo',
      'PaGlubinaToProductVariationConnectionPageInfo',
      'PaShadowGapToContentNodeConnectionPageInfo',
      'PaShadowGapToProductConnectionPageInfo',
      'PaShadowGapToProductVariationConnectionPageInfo',
      'PaWidthToContentNodeConnectionPageInfo',
      'PaWidthToProductConnectionPageInfo',
      'PaWidthToProductVariationConnectionPageInfo',
      'PostFormatToContentNodeConnectionPageInfo',
      'PostFormatToPostConnectionPageInfo',
      'PostToCategoryConnectionPageInfo',
      'PostToCommentConnectionPageInfo',
      'PostToPostConnectionPageInfo',
      'PostToPostFormatConnectionPageInfo',
      'PostToRevisionConnectionPageInfo',
      'PostToTagConnectionPageInfo',
      'PostToTermNodeConnectionPageInfo',
      'ProductCategoryToAncestorsProductCategoryConnectionPageInfo',
      'ProductCategoryToContentNodeConnectionPageInfo',
      'ProductCategoryToProductCategoryConnectionPageInfo',
      'ProductCategoryToProductConnectionPageInfo',
      'ProductTagToContentNodeConnectionPageInfo',
      'ProductTagToProductConnectionPageInfo',
      'ProductToCommentConnectionPageInfo',
      'ProductToCommentsConnectionPageInfo',
      'ProductToGlobalProductAttributeConnectionPageInfo',
      'ProductToLocalProductAttributeConnectionPageInfo',
      'ProductToMediaItemConnectionPageInfo',
      'ProductToPaBacklightsConnectionPageInfo',
      'ProductToPaColorConnectionPageInfo',
      'ProductToPaGlubinaConnectionPageInfo',
      'ProductToPaShadowGapConnectionPageInfo',
      'ProductToPaWidthConnectionPageInfo',
      'ProductToProductCategoryConnectionPageInfo',
      'ProductToProductTagConnectionPageInfo',
      'ProductToProductTypeConnectionPageInfo',
      'ProductToProductUnionConnectionPageInfo',
      'ProductToShippingClassConnectionPageInfo',
      'ProductToTermNodeConnectionPageInfo',
      'ProductToUpsellConnectionPageInfo',
      'ProductToVisibleProductConnectionPageInfo',
      'ProductTypeToContentNodeConnectionPageInfo',
      'ProductTypeToProductConnectionPageInfo',
      'ProductVariationToVariationAttributeConnectionPageInfo',
      'ProductWithAttributesToProductAttributeConnectionPageInfo',
      'ProductWithAttributesToVariationAttributeConnectionPageInfo',
      'ProductWithVariationsToProductVariationConnectionPageInfo',
      'RootQueryToCategoryConnectionPageInfo',
      'RootQueryToCommentConnectionPageInfo',
      'RootQueryToContentNodeConnectionPageInfo',
      'RootQueryToContentTypeConnectionPageInfo',
      'RootQueryToCouponConnectionPageInfo',
      'RootQueryToCustomerConnectionPageInfo',
      'RootQueryToEnqueuedScriptConnectionPageInfo',
      'RootQueryToEnqueuedStylesheetConnectionPageInfo',
      'RootQueryToMediaItemConnectionPageInfo',
      'RootQueryToMenuConnectionPageInfo',
      'RootQueryToMenuItemConnectionPageInfo',
      'RootQueryToOrderConnectionPageInfo',
      'RootQueryToPaBacklightsConnectionPageInfo',
      'RootQueryToPaColorConnectionPageInfo',
      'RootQueryToPageConnectionPageInfo',
      'RootQueryToPaGlubinaConnectionPageInfo',
      'RootQueryToPaShadowGapConnectionPageInfo',
      'RootQueryToPaWidthConnectionPageInfo',
      'RootQueryToPaymentGatewayConnectionPageInfo',
      'RootQueryToPluginConnectionPageInfo',
      'RootQueryToPostConnectionPageInfo',
      'RootQueryToPostFormatConnectionPageInfo',
      'RootQueryToProductCategoryConnectionPageInfo',
      'RootQueryToProductTagConnectionPageInfo',
      'RootQueryToProductTypeConnectionPageInfo',
      'RootQueryToProductUnionConnectionPageInfo',
      'RootQueryToRefundConnectionPageInfo',
      'RootQueryToRevisionsConnectionPageInfo',
      'RootQueryToShippingClassConnectionPageInfo',
      'RootQueryToShippingMethodConnectionPageInfo',
      'RootQueryToShippingZoneConnectionPageInfo',
      'RootQueryToTagConnectionPageInfo',
      'RootQueryToTaxClassConnectionPageInfo',
      'RootQueryToTaxonomyConnectionPageInfo',
      'RootQueryToTaxRateConnectionPageInfo',
      'RootQueryToTermNodeConnectionPageInfo',
      'RootQueryToThemeConnectionPageInfo',
      'RootQueryToUserConnectionPageInfo',
      'RootQueryToUserRoleConnectionPageInfo',
      'RootQueryToVisibleProductConnectionPageInfo',
      'ShippingClassToContentNodeConnectionPageInfo',
      'ShippingClassToProductConnectionPageInfo',
      'ShippingZoneToShippingMethodConnectionPageInfo',
      'SimpleProductToProductUnionConnectionPageInfo',
      'TagToContentNodeConnectionPageInfo',
      'TagToPostConnectionPageInfo',
      'TaxonomyToContentTypeConnectionPageInfo',
      'TaxonomyToTermNodeConnectionPageInfo',
      'TermNodeToEnqueuedScriptConnectionPageInfo',
      'TermNodeToEnqueuedStylesheetConnectionPageInfo',
      'UserToCommentConnectionPageInfo',
      'UserToEnqueuedScriptConnectionPageInfo',
      'UserToEnqueuedStylesheetConnectionPageInfo',
      'UserToMediaItemConnectionPageInfo',
      'UserToPageConnectionPageInfo',
      'UserToPostConnectionPageInfo',
      'UserToRevisionsConnectionPageInfo',
      'UserToUserRoleConnectionPageInfo',
      'VariableProductToProductUnionConnectionPageInfo',
      'VisibleProductToContentNodeConnectionPageInfo',
      'VisibleProductToProductConnectionPageInfo',
    ],
  },
};
export default result;
