import type { Metadata } from 'next';
import { Montserrat, Inter } from 'next/font/google';
import './globals.scss';
import HeaderComponent from '@/shared/ui/layout/HeaderComponent/HeaderComponent';
import React from 'react';
import FooterComponent from '@/shared/ui/layout/FooterComponent/FooterComponent';
import NavigationBar from '@/shared/ui/layout/NavigationBar/NavigationBar';

const fontMontserrat = Montserrat({
  variable: '--font-montserrat-sans',
  subsets: ['cyrillic'],
  style: ['normal'],
});

const fontInter = Inter({
  variable: '--font-inter-sans',
  subsets: ['cyrillic'],
  weight: ['400'],
});

// const centuryGothic = localFont({
//   src: [
//     {
//       path: '../../public/fonts/CenturyGothic/CenturyGothic_Regular.woff',
//       weight: '400',
//       style: 'normal',
//     },
//     {
//       path: '../../public/fonts/CenturyGothic/CenturyGothic_Regular.woff2',
//       weight: '400',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-century-gothic',
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontMontserrat.variable} ${fontInter.variable} antialiased`}
      >
        <HeaderComponent />
        <main>{children}</main>
        <FooterComponent />
        <NavigationBar />
      </body>
    </html>
  );
}
