import type { Metadata } from 'next';
import { Montserrat, Inter } from 'next/font/google';
import './globals.scss';
import HeaderComponent from '@/components/HeaderComponent/HeaderComponent';
import React from 'react';

const fontMontserrat = Montserrat({
  variable: '--font-montserrat-sans',
  subsets: ['cyrillic'],
  style: ['normal', 'italic'],
});

const fontInter = Inter({
  variable: '--font-inter-sans',
  subsets: ['cyrillic'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontMontserrat.variable} ${fontInter.variable} antialiased`}
      >
        <HeaderComponent />
        <main>{children}</main>
      </body>
    </html>
  );
}
