import './globals.scss';
import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Montserrat, Inter } from 'next/font/google';

import HeaderComponent from '@/shared/ui/layout/HeaderComponent/HeaderComponent';
import FooterComponent from '@/shared/ui/layout/FooterComponent/FooterComponent';
import NavigationBar from '@/shared/ui/layout/NavigationBar/NavigationBar';
import { ApolloProvider } from '@/app/lib/apollo/provider';
import { MenuProvider } from '@/context/MenuContext';
import SideMenuComponent from '@/shared/ui/layout/SideMenuComponent/SideMenuComponent';
import HeroProviders from '@/shared/ui/layout/HeroProviders/HeroProviders';

const fontMontserrat = Montserrat({
  variable: '--font-montserrat-sans',
  subsets: ['cyrillic'],
  style: ['normal'],
});

const fontInter = Inter({
  variable: '--font-inter-sans',
  subsets: ['cyrillic'],
  weight: ['400'],
});

const centuryGothic = localFont({
  src: [
    {
      path: '../shared/assets/fonts/CenturyGothic/CenturyGothic_Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../shared/assets/fonts/CenturyGothic/CenturyGothic_Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-century-gothic-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${fontMontserrat.variable} ${fontInter.variable} ${centuryGothic.variable}`}
      >
        <ApolloProvider>
          <MenuProvider>
            <HeaderComponent />
            <SideMenuComponent />
            <main>{children}</main>
            <FooterComponent />
            <NavigationBar />
          </MenuProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
